E_COM/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('seller/', include('seller.urls')),
    
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core import views


urlpatterns = [
    path('', views.index,name='index'),
    path('product_desc/<pk>', views.product_desc,name='product_desc'),
    path('add_to_cart/<pk>', views.add_to_cart,name='add_to_cart'),
    path('order_list', views.order_list,name='order_list'),
    path('add_item/<int:pk>', views.add_item,name='add_item'),
    path('remove_item/<int:pk>', views.remove_item,name='remove_item'),
    
    path('checkout_page/<int:id>', views.checkout_page,name='checkout_page'),
    path('orders', views.orders_view,name='orders'),
    
    path('create-payment-intent/', views.create_payment_intent, name='create_payment_intent'),
    path('payment-confirm/<str:payment_intent_id>/<int:id>/', views.payment_confirm, name='payment_confirm'),
    path('confirm-payment/<int:id>/', views.confirm_payment, name='confirm_payment'),
    path('payment_failed/', views.payment_failed, name='payment_failed'),
    path('search/', views.home, name='home'),
    path('add_category/', views.add_category, name='add_category'),
    path('orders/', views.all_orders, name='all_orders'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django_countries.fields import CountryField
from django.urls import reverse
from .models import *



# Create your models here.

class Customer(models.Model):
    
    user = models.OneToOneField(User,null=False,blank=False,on_delete = models.CASCADE)
    
    #extra fields will come here
    phone_field = models.CharField(max_length=12,blank=False)
    
    def __str__(self):
        return self.user.username
    
class Category(models.Model):
    category_name = models.CharField(max_length=200)
    
    def __str__(self):
        return self.category_name
    
    
class Product(models.Model):
    name = models.CharField(max_length=100)
    category = models.ForeignKey('Category',on_delete=models.CASCADE,related_name='products')
    desc = models.TextField()
    price = models.FloatField(default=0.0)
    product_available_count = models.IntegerField(default=0)
    img = models.ImageField(upload_to='images')
    
    
    
    def get_add_to_cart_url(self):
        return reverse('core:add-to-cart', kwargs={
            'pk' : self.pk
        })
        
    def __str__(self):
        return self.name
        
        
class OrderItem(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    
    
    def __str__(self):
        return f"{self.quantity} of {self.product.name}"
    
    def get_total_item_price(self):
        return self.quantity * self.product.price

    def get_final_price(self):
        return self.get_total_item_price()
    
class Order(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField(auto_now_add=True)
    ordered = models.BooleanField(default=False)
    order_id = models.CharField(max_length=100,unique=True,default=None,blank=True,null=True)
    datetime_ofpayment = models.DateTimeField(auto_now_add=True)
    order_delivered = models.BooleanField(default=False)
    order_received = models.BooleanField(default=False)
    is_paid = models.BooleanField(default=False)
    
   
    
    #razorpay_order_id = models.CharField(max_length=500,null=True,blank=True)
    #razorpay_payment_id = models.CharField(max_length=500,null=True,blank=True)
    #razorpay_signature = models.CharField(max_length=500,null=True,blank=True)
    
    def save(self,*args,**kwargs):
        if self.order_id is None and self.datetime_ofpayment and self.id:
            self.order_id = self.datetime_ofpayment.strftime("PAY2ME%Y%m%dODR") + str(self.id)
            
        return super().save(*args,**kwargs)
    def __str__(self):
        return self.user.username
    
    def get_total_price(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total
    
    def get_total_count(self):
        order = Order.objects.get(pk=self.pk)
        return order.items.count()
    
class CheckOutAddress(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip_code = models.CharField(max_length=100)
    
    def __str__(self):
        return self.user.username
    


    

core/forms.py
from django import forms
from core.models import *
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        
class CheckoutForm(forms.Form):
    
    street_address = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control',
        'placeholder':'1234 Main St'
    }))
    apartment_address = forms.CharField(required=False,widget=forms.TextInput(attrs={
        'class':'form-control',
        'placeholder':'Apartment or suite'
    }))
    country = CountryField(blank_label='(select country)').formfield(widget=CountrySelectWidget(attrs={
        'class': 'custom-select d-block w-100'
    }))
        
        
    zip = forms.CharField(widget=forms.TextInput(attrs={
        'class':'flow-control'
    }))
    
    
class SearchForm(forms.Form):
    query = forms.CharField(label='Search', max_length=100, required=False)
    
    
class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['category_name']

core/views.py
from django.shortcuts import render,redirect,get_object_or_404
from core.forms import *
from django.contrib import messages
from core.models import *
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.http import JsonResponse
import stripe
from core.models import OrderItem,Order
from django.core.mail import send_mail
from datetime import datetime
from .forms import SearchForm
from django.core.paginator import Paginator
from .stripe_utils import create_payment_intent
stripe.api_key = settings.STRIPE_SECRET_KEY
YOUR_DOMAIN = 'http://localhost:8000'




# Create your views here.
def index(request):
    items = Product.objects.all().order_by('id')
    paginator = Paginator(items, 3)
    page_number = request.GET.get("page")
    products = paginator.get_page(page_number)


    return render(request,'core/index.html',{'products':products})




def order_list(request):
    if Order.objects.filter(user=request.user,ordered=False).exists():
        order = Order.objects.get(user = request.user,ordered = False)
        return render(request,'core/order_list.html',{'order':order})
    return render(request,'core/order_list.html',{'message':"Your cart is empty"})
        

def product_desc(request,pk):
    product = Product.objects.get(pk=pk)
    images = product.img
    print(images,"images here")
    return render(request,'core/product_desc.html',{'product':product,"images":images})
    
def add_to_cart(request,pk):
    product = Product.objects.get(pk=pk)
    
    #Create Order item
    order_item, created = OrderItem.objects.get_or_create(
        product = product,
        user = request.user,
        ordered = False,
    )
     
    #get query set of order object of perticular user
    order_qs = Order.objects.filter(user=request.user,ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(product__pk = pk).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request,"Added Quantity item..")
            return redirect('product_desc',pk=pk)
        else:
            order.items.add(order_item)
            messages.info(request,"Item Added to cart..")
            return redirect('product_desc',pk=pk)
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(user=request.user,ordered_date=ordered_date)
        order.items.add(order_item)
        messages.info(request,"item added to cart")
        return redirect('product_desc',pk=pk)
    


def add_item(request,pk):
    
    product = Product.objects.get(pk=pk)  #get a perticuler Product of id = pk
    
    
    order_item, created = OrderItem.objects.get_or_create(
        product = product,
        user = request.user,
        ordered = False,
    )                                      #Create Order item
     
    
    order_qs = Order.objects.filter(user=request.user,ordered=False) #get query set of order object of perticular user
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(product__pk = pk).exists():
            if order_item.quantity < product.product_available_count:
                order_item.quantity += 1
                order_item.save()
                messages.info(request,"Added Quantity item..")
                return redirect('order_list')
            else:
                messages.info(request,"Sorry Product is out of stock")
                return redirect('order_list')
        else:
            order.items.add(order_item)
            messages.info(request,"Item Added to cart..")
            return redirect('product_desc',pk=pk)
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(user=request.user,ordered_date=ordered_date)
        order.items.add(order_item)
        messages.info(request,"item added to cart")
        return redirect('product_desc',pk=pk)
      

def remove_item(request,pk):
    item = get_object_or_404(Product,pk=pk)
    order_qs = Order.objects.filter(
        user = request.user,
        ordered = False,
    )
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(product__pk = pk).exists():
            order_item = OrderItem.objects.filter(
               product = item,
               user = request.user,
               ordered = False, 
            )[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
            else:
                order_item.delete()
            messages.info(request,"Item quantity was updated")
            return redirect('order_list')
        else:
            messages.info(request,"This item is not in cart")
            return redirect('order_list')
    else:
        messages.info(request,'You do not have any order')
        return redirect('order_list')
    
def checkout_page(request,id):
    request.session['id']=id
    
    if CheckOutAddress.objects.filter(user=request.user).exists():
        return render(request,'core/checkout_address.html',{'payment_allow':'allow'})
    
    if request.method == 'POST':
        form = CheckoutForm(request.POST)
        try:
            if form.is_valid():
                street_address = form.cleaned_data.get('street_address')
                apartment_address = form.cleaned_data.get('apartment_address')
                country = form.cleaned_data.get('country')
                zip_code = form.cleaned_data.get('zip')
                
                checkout_address = CheckOutAddress(
                    user = request.user,
                    street_address = street_address,
                    apartment_address = apartment_address,
                    country = country,
                    zip_code = zip_code,
                )
                
                checkout_address.save()
                print('It should render the summary page')
                return render(request,'core/checkout_address.html',{'payment_allow':'allow'})
        except Exception as e:
            messages.warning(request,"Failed checkout")
            return redirect('checkout_page') 
    
    else:
        form = CheckoutForm()
        return render(request,'core/checkout_address.html',{'form':form})
    
 

 
 
    
@login_required
def orders_view(request):
    
    orders = Order.objects.filter(user=request.user, is_paid=True).prefetch_related('items__product')
    
    return render(request, 'core/user_orders.html', {'orders': orders})


def create_payment_intent(request):
    if request.method == 'GET':
        try:
            id = request.session['id']
            order = OrderItem.objects.get(id=id)  
            total_price = order.get_final_price()
            request.session['total_price']=total_price
            amount = total_price
            print(amount) 
            intent = stripe.PaymentIntent.create(
                amount=100,
                currency='usd',
                payment_method_types=['card'],
                payment_method="pm_card_visa",
                metadata={'order_id': id}
            )
            payment_intent_id = intent.id
            request.session['payment_intent_id']=payment_intent_id
            
            client_secret = intent.client_secret
            
            if intent and intent.client_secret:
                return redirect('payment_confirm',  payment_intent_id=payment_intent_id, id=id)
            else:
                return JsonResponse({'error': 'Failed to create PaymentIntent'}, status=400)
        
        except stripe.error.StripeError as e:
            return JsonResponse({'error': str(e)}, status=400)
    
    return JsonResponse({'error': 'Invalid request method'}, status=405)





def payment_confirm(request, payment_intent_id, id):
    return render(request, 'payment/payment_confirm.html', {'payment_intent_id': payment_intent_id, 'id': id})


@login_required(login_url='user_login')
def confirm_payment(request, id):
    if request.method == 'POST':
        
        payment_intent_id = request.session.get('payment_intent_id')
        print(payment_intent_id)
        try:
            payment_intent = stripe.PaymentIntent.retrieve(payment_intent_id)
            print(payment_intent)
            #if payment_intent status is already succeeded
            if payment_intent.status == 'requires_confirmation':
                payment_intent = stripe.PaymentIntent.confirm(payment_intent_id)
            if payment_intent.status == 'succeeded':
                
                payment_datetime = datetime.fromtimestamp(payment_intent.created)
                
                #create the Order
                order, created = Order.objects.get_or_create(
                    id=id,
                    defaults={
                        'user': request.user,
                        'ordered': True,
                        'order_id': payment_intent.id,
                        'datetime_ofpayment': payment_datetime,
                    }
                )
                print(order)
                if not created:
                    order.ordered = True
                    order.order_id = payment_intent.id
                    order.datetime_ofpayment = payment_datetime
                    order.save()
                
               
                order.items.clear()
                item = get_object_or_404(OrderItem, id=id)
                item.ordered = True
                item.save()
                order.items.add(item)
                print(item)
                
                #confirmation email
                total_price = request.session.get('total_price')
                subject = "Payment status"

templates/core/add_category.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Add Category</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link href="{% static 'css/login.css'%}" rel="stylesheet">

</head>
<body>
    <form method="POST">
        <h2>Add Category</h2>
        {% csrf_token %}
        {{ form }}
        <button type="submit">Add Category</button>
    </form>
    <script src="{% static 'js/main.js'%}"></script>

</body>
</html>

templates/core/add_product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Product</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>
<body>
        {% if messages %}
        {% for message in messages %}
        <h3 style="color:red;">{{message}}</h3>
        {% endfor %}
        {% endif %}

    <form method="post" enctype="multipart/form-data">
        <h2>Add Product</h2>
        {% csrf_token %}
        
        {{ form.as_p }}
        <button class="btn btn-primary btn-lg" type="submit">Add</button><br>
    </form>
</body>
    
            



              

templates/core/checkout_address.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Checkout Page</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>
<body>
    <div>
    {% if payment_allow == 'allow' %}
    <a href="{% url 'create_payment_intent' %}" class="btn btn-primary">Go for Payment</a>
    {% else %}
    
    {% if messages %}
    {% for message in messages %}
    <h3 style="color:red;">{{message}}</h3>
    {% endfor %}
    {% endif %}
    
    <form method="post">
        <h2>Checkout Address</h2>
        {% csrf_token %}
        {{form}}
        <button class="btn btn-primary btn-lg" type="submit">Checkout</button><br>
    </form>
    {% endif %}
    </div>
</body>
    
            



              

templates/core/index.html
<!DOCTYPE html>
{% load static %}
{% load cart_template_tag %}

<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>P-Cart Online Shopping</title>
  <meta name="description" content="">
  <meta name="keywords" content="">

  <!-- Favicons -->
  
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Fonts -->
  <link href="https://fonts.googleapis.com" rel="preconnect">
  <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css'%}" rel="stylesheet">
  <link href="{% static 'vendor/aos/aos.css'%}" rel="stylesheet">
  <link href="{% static 'vendor/glightbox/css/glightbox.min.css'%}" rel="stylesheet">
  <link href="{% static 'vendor/swiper/swiper-bundle.min.css'%}" rel="stylesheet">

  <!-- Main CSS File -->
  <link href="{% static 'css/main.css'%}" rel="stylesheet">
  <link href="{% static 'css/home_product.css'%}" rel="stylesheet">
  
</head>

<body class="index-page">
  


  <header id="header" class="header d-flex align-items-center fixed-top">
    
    <div class="header-container container-fluid container-xl position-relative d-flex align-items-center justify-content-end">

      <a href="index.html" class="logo d-flex align-items-center me-auto">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="assets/img/logo.png" alt=""> -->
        <h1 class="sitename">P - CART</h1>
      </a>
      
      <nav id="navmenu" class="navmenu">
        <ul>
          <li>
            <form method="GET" action="{% url 'home' %}" class="d-flex align-items-center">
              <input type="text" name="query" id="id_query" class="form-control me-2" placeholder="Search Here" value="{{ request.GET.query }}">
              <button type="submit" class="btn btn-primary">Search</button>
            </form>
          </li>
          <li><a href="{% url 'index' %}" class="active">Home</a></li>

          {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Hello-{{ user.username }}</a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li>
                <a href="{% url 'order_list' %}" class="active">Cart&nbsp;&nbsp;
                  <div style="color:red;">{{ request.user | cart_item_count }}</div>
                </a>
              </li>
              
              {% if user.is_staff %}
              <li><a class="dropdown-item" href="{% url 'add_product' %}">Add Product</a></li>
              {% endif %}

              {% if user.is_superuser %}
                <li><a class="dropdown-item" href="{% url 'add_category' %}">Add Category</a></li>
                <li><a href="{% url 'all_orders' %}" class="active">All Orders</a></li>
              {% endif %}
        
              <li><a class="dropdown-item" href="{% url 'orders' %}">Orders</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'user_logout' %}">Logout</a></li>
            </ul>
          </li>
        {% else %}
          <li><a href="{% url 'user_login' %}" class="active">Login</a></li>
        {% endif %}
        </ul>
        <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
      </nav>
    </div>
  </header>

  <main class="main">
  

    <!-- Hero Section -->
    <section id="hero" class="hero section dark-background">

      <img src="{% static 'img/hero-bg.jpg'%}" alt="" data-aos="fade-in" class="aos-init aos-animate">

      <div class="container text-center aos-init aos-animate" data-aos="fade-up" data-aos-delay="100">
        <div class="row justify-content-center">
          <div class="col-lg-8">
            <h2>Transform Your World</h2>
          </div>
        </div>
      </div>
    </section>
  
  
    <!-- Stats Section -->
    <section>

      <div class="container">
        {% if user.is_superuser and user.is_staff%}
        <div class='alert alert-info'>
          <p>This is Admin</p>
        </div>
        

        {% elif user.is_staff %}
        <div class='alert alert-info'>
          <p>This is Seller</p>
        </div>
        {% endif %}
      </div>

    </section>


    
      <div class="container">
          <div class="row  ">
              
            {% for product in products %}
            <div class="col-md-4">
            <div class="card" style="width: 18rem;">
              <img class="card-img-top product-image" src="{{ product.img.url }}" alt="Card image cap">
              <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
              </div>
              <ul class="list-group list-group-flush">
                <li class="list-group-item"><b>Category</b> : {{product.category.category_name}}</li>
                <li class="list-group-item"><b>Price</b> : {{product.price}}</li>
              </ul>
              <div class="card-body">
                <a href="{% url 'product_desc' product.pk %}" class="btn btn-dark">View</a>
              </div>
            </div>
            </div>
            {% endfor %}
            <center>
              <div class="pagination">
                <span class="step-links">
                  
                    {% if products.has_previous %}
                        <a href="?page={{ products.previous_page_number }}">Previous</a>&nbsp;&nbsp;
                    {% endif %}
                    <span class="current">
                      Page {{ products.number }} of {{ products.paginator.num_pages }}&nbsp;&nbsp;
                    </span>
                    {% if products.has_next %}
                        <a href="?page={{ products.next_page_number }}">Next</a>&nbsp;&nbsp;
                    {% endif %}
                  
                </span>
              </div>
            </center>
          </div>
      </div>
    </section>
    </main>




  

         


  <!-- Vendor JS Files -->
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
  <script src="{% static 'vendor/php-email-form/validate.js'%}"></script>
  <script src="{% static 'vendor/aos/aos.js'%}"></script>
  <script src="{% static 'vendor/glightbox/js/glightbox.min.js'%}"></script>
  <script src="{% static 'vendor/purecounter/purecounter_vanilla.js'%}"></script>
  <script src="{% static 'vendor/imagesloaded/imagesloaded.pkgd.min.js'%}"></script>
  <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js'%}"></script>
  <script src="{% static 'vendor/swiper/swiper-bundle.min.js'%}"></script>

  <!-- Main JS File -->
  <script src="{% static 'js/main.js'%}"></script>

</body>

</html>

templates/core/order_list.html
<!DOCTYPE html>
{% load static %}
{% load cart_template_tag %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>order_list</title>
    <script src="https://js.stripe.com/v3/"></script>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
            
        }
        .container {
            max-width: 1200px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
        }
        

        table {
            text-align: center;
        }

        .product-list {
            list-style: none;
            padding: 0;
        }
        .product-item {
            
            justify-content: space-between;
            align-items: center;
            padding: 20px;
        }
        
        .product-details {
            flex: 2;
            margin-left: 20px;
        }
        .product-price {
            font-weight: bold;
            padding: 20px
        }
        .add-to-cart-btn {
            background-color: #28a745;
            color: #fff;
            border: none;
            padding: 10px 15px;
            cursor: pointer;
        }
        .add-to-cart-btn:hover {
            background-color: #218838;
        }
    </style>
    <link href="{% static 'css/main.css'%}" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
</head>
    <header>
        {% if messages %}
            <div class="alert alert-info" role="alert">
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            </div>
        {% endif %}
    </header>

<body>
    <center>
        <section class="inner-page">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card-shadow">
                            <div class="card-body">
                            
                            <h1><span>Your Cart</span></h1><br>
                            <table border="1" style="width: 1000px;">
                                <thead>
                                    <tr>
                                        <th scope="col">No</th>
                                        <th scope="col">Item Name</th>
                                        <th scope="col">Price</th>
                                        <th scope="col">Quantity</th>
                                        <th scope="col">Total Item price</th>
                                        <th scope="col">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for order_item in order.items.all %}
                                    <tr>
                                        <th scope="row">{{forloop.counter}}</th>
                                        <td class="product-item">{{ order_item.product.name }}</td>
                                        <td class="product-price">{{ order_item.product.price }}</td>
                                        
                                        <td style="padding: 20px;">
                                            <a href="{% url 'remove_item' order_item.product.pk %}">-</a> &nbsp;&nbsp;
                                            {{ order_item.quantity }} &nbsp;&nbsp;
                                            <a href="{% url 'add_item' order_item.product.pk %}">+</i></a>
                                        </td>
                                        <td>Rs. {{ order_item.get_total_item_price }}</td>
                                        <td>
                                            <a href="{% url 'checkout_page' order_item.id %}" class="add-to-cart-btn">Cheakout</a>
                                        </td>
                                    </tr>
                                    {% empty %}
                                    <tr class="row100 body">
                                        <td class="cell100 column1" colspan="6">Your cart is Empty</td>
                                    </tr>
                                    
                                    
                                    
                                    {% endfor %}
                                    
                                    {% if order.get_total_price %}
                                    <tr class="row100 body"style=background-color:#191919>
                                        <td class="cell100 column1" style="color:white;"><b>Total Price</b></td>
                                        <td class="cell100 column2"></td>
                                        <td class="cell100 column3"></td>
                                        <td class="cell100 column4"></td>
                                        <td class="cell100 column5" style="color:white;">
                                            <i class="fas fa-rupee-sign"></i> Rs.{{order.get_total_price}}
                                        </td>
                                    </tr>
                                    {% endif %}
                                </tbody>
                            </table><br>
                            <tr class="row100 body">
                                <td class="cell100 column1">
                                    <a href="{% url 'index' %}" class="btn btn-primary">Continue Shopping</a>
                                </td>
                            </tr>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </center>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>